trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@1
  displayName: Azure CLI
  inputs:
    azureSubscription: azure sp resource manager
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show

# - script: |
#     terraform init
#     terraform validate
#   displayName: 'Terraform init and validate'
