trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
# - task: AzureCLI@1
#   displayName: Azure CLI
#   inputs:
#     azureSubscription: 'azure sp resource manager'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az login

- script: |
    terraform init -backend=true \
                   -backend-config="resource_group_name=state-rg" \
                   -backend-config="storage_account_name=terraformstorageo" \
                   -backend-config="container_name=state" \
                   -backend-config="key=terraform.tfstate"
    terraform validate
    terraform plan
  displayName: 'Terraform init and validate'
