trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-vars

steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure sp resource manager'
    backendAzureRmResourceGroupName: '$(backend-rg)'
    backendAzureRmStorageAccountName: '$(backend-storage-name)'
    backendAzureRmContainerName: '$(backend-container-name)'
    backendAzureRmKey: '$(backend-key)'

- task: TerraformTaskV4@4
  displayName: 'Terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    environmentServiceNameAzureRM: 'azure sp resource manager'

- task: TerraformTaskV4@4
  displayName: 'Terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure sp resource manager'
    backendServiceArm: 'azure sp resource manager'    
    backendAzureRmResourceGroupName: '$(backend-rg)'
    backendAzureRmStorageAccountName: '$(backend-storage-name)'
    backendAzureRmContainerName: '$(backend-container-name)'
    backendAzureRmKey: '$(backend-key)'  
  env:
    mssql_server_login: $(mssql_server_login)
    mssql_server_password: $(mssql_server_password)