trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  backend-rg: 'state-rg'
  backend-storage-name: 'terraformstorageo'
  backend-container-name: 'state'
  backend-key: 'terraform.tfstate'


steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure sp resource manager'
    backendAzureRmResourceGroupName: '$(backend-rg)'
    backendAzureRmStorageAccountName: '$(backend-storage-name)'
    backendAzureRmContainerName: '$(backend-container-name)'
    backendAzureRmKey: '$(backend-key)'

# - script: |
#     terraform init -backend=true \
#                    -backend-config="resource_group_name=" \
#                    -backend-config="storage_account_name=" \
#                    -backend-config="container_name=" \
#                    -backend-config="key="
#     terraform validate
#     terraform plan
#   displayName: 'Terraform init and validate'
