trigger:
  branches:
    include:
      - main

pr: none

variables:
- group: terraform-vars

stages:
- stage: Deploy_terraform_reaources
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: Deploy_terraform_reaources
      steps:
        - task: TerraformTaskV4@4
          displayName: 'Terraform init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'azure sp resource manager'
            backendAzureRmResourceGroupName: '$(backend-rg)'
            backendAzureRmStorageAccountName: '$(backend-storage-name)'
            backendAzureRmContainerName: '$(backend-container-name)'
            backendAzureRmKey: '$(backend-key)'

        - task: TerraformTaskV4@4
          displayName: 'Terraform validate'
          inputs:
            provider: 'azurerm'
            command: 'validate'
            environmentServiceNameAzureRM: 'azure sp resource manager'
        - task: TerraformTaskV4@4
          displayName: 'Terraform apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'azure sp resource manager'
            commandOptions: '-var="client_id=$(AZURE_CLIENT_ID)" -var="client_secret=$(AZURE_CLIENT_SECRET)" -var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var="tenant_id=$(AZURE_TENANT_ID)"'